version: "3.8"

services:
  postgresql:
    image: postgres:15-alpine
    container_name: avito-postgres
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - avito-ms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_interval: 2s

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito-microservice
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - avito-ms-network

volumes:
  postgresql-data:

networks:
  avito-ms-network:
    driver: bridge